theme: minima
title: first_try_landed_blog
author: krlz
description: Reflections on stuff as it happens
email: cpumarfrohberg@example.com
baseurl: ""
url: "https://cpumarfrohberg.github.io"
github_username: cpumarfrohberg