title: first_try_landed_blog
description: Reflections on stuff as it happens
baseurl: "/first_try_landed"
url: "https://cpumarfrohberg.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag